### ISSUE TITLE
EEPROM Checksum test

### ISSUE THREAD

**Issue by shengwen1997** [UrsusPilot/firmware#165]
[Simple implementation of LRC checksum](https://github.com/shengwen1997/firmware/blob/215b40f90adf6bd7aec96d72521cf87a6e85bc6a/program/mavlink/checksum.c)

[Ref: LRC](http://en.wikipedia.org/wiki/Longitudinal_redundancy_check)

**Comment by fboris** [comment]
It is also possible to use CRC(Cyclic redundancy check). Mavlink has already implemented it.
